name: Lintv2

on:
  pull_request_target:

permissions:
  contents: read          # Required for repository access
  pull-requests: write    # Required to update PR status
  checks: write           # Required to create check run annotations

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the base repository
      - name: Check out base repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      # Step 2: Add the fork as a remote (if needed)
      - name: Add fork as remote
        if: github.event.pull_request.head.repo.full_name != github.repository
        run: |
          git remote add fork https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
          git fetch fork
          git checkout -b pr-branch fork/${{ github.event.pull_request.head.ref }}

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      # Step 4: Install linter dependencies
      - name: Install Python dependencies
        run: pip install black==22.12.0 flake8==5.0.4

      # Step 5: Run linters (Black and Flake8)
      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          black: true
          flake8: true
